# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ana Villa
title: Software Engineer
email: villameza.ana@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  avillameza
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ana-villa-03817367
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Hi, I'm Ana. I really enjoy making things, whether it be in a computer, machine shop, or sketchbook. 
  I have diverse experience working in software, biotech, and machine shops. 

  # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Focus LoFi
        link: https://github.com/Avillameza/focus_lo_fi
        # link_text: Project Website
        additional_links:
          - title:  Focus LoFi
            icon: fab fa-github
            url: https://github.com/Avillameza/react_youtube
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
           A responsive web app with an API to play Youtube playlists from the Youtube API with a <mark>Ruby on Rails</mark> backend and <mark>React</mark> frontend.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amplio Inc
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Junior Software Engineer
        caption: March 2022 - November 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Collaborated with operations, engineers, and clients in the full-stack deployment of a product in 3 months in an agile early-stage startup with CI/CD pipelines.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvey Mudd College
        caption: 2012 - 2016
        sub_title: Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Mudd, I learned a lot about different engineering disciplines, from mechanical to software.

          I was part of the Society of Women Engineers chapter from freshman to senior year, holding positions such as Events Coordinator and Co-president. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In addition to my love of engineering, I also love drawing.
      # - Drawing
    

      # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  
      # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
